#!/bin/bash

! command -v zip &> /dev/null && exit 17
! command -v jq  &> /dev/null && exit 18

cd "$(dirname "$0")"

mkdir -p output

cd pack

NAME=$(jq -r ".name" modrinth.index.json)
VERSION=$(jq -r ".versionId" modrinth.index.json)

zip -FSr9 "../output/${NAME} v${VERSION}.mrpack" .
